<?php

namespace ContactBundle\Repository;

/**
 * ContactRepository
 *
 * This class was generated by the Doctrine ORM. Add your own custom
 * repository methods below.
 */
class ContactRepository extends \Doctrine\ORM\EntityRepository
{
    public function getAllContacts($objet)
    {
        $qb = $this->createQueryBuilder('c');

        /**
         * recherche via l'objet
         */
        if(!empty($objet)){
            $qb->andWhere('c.objet = :objet')
               ->setParameter('objet', $objet);
        }

        $qb->orderBy('c.id', 'DESC');

        return $query = $qb->getQuery()->getResult();
    }
}
